### PR TITLE
Update serviio to 1.7 version

### PR DESCRIPTION
**Pull request by Kwull**

### CODE REVIEW

**Comment by sparklyballs** [comment]
test this please

**Comment by Kwull** [comment]
Please take into account that in [89835aa](https://github.com/linuxserver/docker-serviio/pull/8/commits/89835aacfc0ec65d7a08dd4d3cc15f583e382aaf) I've made a breaking change in configuration folder. I've removed redundant 'serviio' path part from /config/serviio/config

**Review by sparklyballs — CHANGES_REQUESTED** [review]
I'm loathe to make this change, existing users are going to be wondering where their settings have gone.

Not to say it isn't redundant though.

**Review by sparklyballs — APPROVED** [review]

**Comment by sparklyballs** [comment]
i'll close the PR, re-raise another and credit you in the changenotes.

I thought the new review system was smarter on multiple commits in a PR.

**Comment by Kwull** [comment]
No problem. I just doing it for myself :) And if it will be useful for someone else it would be great. BTW, do you have a mechanism to add serviio license file? If no... I will add that...

**Pull request closed without merging**
